name: Daily Gold Scrape to Google Sheet

on:
  schedule:
    - cron: "30 0 * * *"   # 00:30 UTC = 06:00 IST
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas gspread gspread-dataframe google-auth playwright

      - name: Install Playwright browsers and deps
        run: |
          python -m playwright install --with-deps chromium

      - name: Run scraper
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          # You can tweak these without editing code:
          SHEET_NAME: Gold Prices (MMTC-PAMP)
          SHEET_TAB: Daily
          PAGE_TIMEOUT_MS: "90000"
          HEADLESS: "true"
        run: |
          python gold_scrape_to_sheet.py

      # If something failed, upload page screenshot & HTML for diagnosis
      - name: Upload debug artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-snapshots
          path: |
            page.png
            page.html
