name: Daily Gold Scrape to Google Sheet

on:
  schedule:
    - cron: "30 0 * * *"   # 00:30 UTC = 06:00 IST
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas gspread gspread-dataframe google-auth playwright

      # Installs browsers & OS deps that Playwright needs (no driver mismatches ever)
      - name: Install Playwright browsers
        uses: microsoft/playwright-github-action@v1
        with:
          with-deps: true
          # browser: chromium  # default includes all; uncomment to limit

      - name: Run scraper
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          python gold_scrape_to_sheet.py
