name: Daily Gold Scrape to Google Sheet

on:
  schedule:
    - cron: "30 0 * * *"   # 00:30 UTC = 06:00 IST
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas gspread gspread-dataframe google-auth selenium webdriver-manager

      - name: Run scraper
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
        run: |
          python gold_scrape_to_sheet.py
