name: Daily Gold Scrape to Google Sheet

on:
  schedule:
    - cron: "30 0 * * *"   # 00:30 UTC = 06:00 IST
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-22.04   # jammy is fully supported by Playwright installers
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas gspread gspread-dataframe google-auth playwright

      # Install Playwright browsers + system deps (supported on 22.04)
      - name: Install Playwright browsers and deps
        run: |
          python -m playwright install --with-deps chromium

      - name: Run scraper
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          python gold_scrape_to_sheet.py
